eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
server:
  port: 8763
 # context-path: /eruka-client 不要起名字 否则注册能成功 但是无法被访问到
spring:
  application:
    name: service-hi