eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.18:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8764
spring:
  application:
    name: service-ribbon 
    